export const FETCHING_FEED_ITEMS = "feed.FETCHING_FEED_ITEMS";
export const FEED_ITEMS_FETCHED = "feed.FEED_ITEMS_FETCHED";
export const FEED_ITEMS_FETCH_ERROR = "feed.FEED_ITEMS_FETCH_ERROR";

export const LOADING_VIDEO = "item.LOADING_VIDEO";
export const VIDEO_LOADING_SUCCESS = "item.VIDEO_LOADING_SUCCESS";
export const VIDEO_LOADING_ERROR = "item.VIDEO_LOADING_ERROR";

export const UPDATE_SOURCE_SELECTION = "sourceSelect.VIDEO_SOURCE_SELECTION";
